version: '2'

services:

  app:
    build: ./docker/app/
    volumes:
    - ./app/src:/app/src
    - ./data:/app/data
    - ./logs:/app/logs

  sl:
    extends:
      service: app
    command: python src/chess_zero/run.py sl

  self:
    extends:
      service: app
    command: python src/chess_zero/run.py self

  opt:
    extends:
      service: app
    command: python src/chess_zero/run.py opt

  eval:
    extends:
      service: app
    command: python src/chess_zero/run.py eval

  gui:
    extends:
      service: app
    command: python src/chess_zero/run.py play_gui

  uci:
    extends:
      service: app
    command: python src/chess_zero/run.py uci

  web:
    build: ./docker/web/
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongodb/web
    volumes:
      - ./web:/home/node/web
    ports:
      - 50080:3000
    links:
      - mongodb

  mongodb:
    image: mongo:3.6.0-jessie
