version: '2'

services:

  app:
    build: ./docker/app/
    volumes:
    - ./app/src:/app/src
    - ./data:/app/data
    - ./logs:/app/logs

  self:
    extends:
      service: app
    command: python src/chess_zero/run.py self

  gui:
    extends:
      service: app
    command: python src/chess_zero/run.py play_gui
