
FROM python:3.6.3-jessie
MAINTAINER Francesco Bianco

RUN cd /app && git clone https://github.com/Zeta36/chess-alpha-zero

WORKDIR /app

RUN pip install -r requirements.txt

CMD ["python", "src/chess_zero/run.py", "self"]
